id: I6B8A2BB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:05:38+00:00'
last_modified: '2022-06-08T07:03:25.585085+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18508
  title: མགོ་ལོག་དམངས་ཁྲོད་ཀྱི་གླིང་གེ་སར་རིག་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '5454':
      image_group_id: I8LS18510
      title: ''
      total_pages: 155
      order: 1
      base_file: 5454.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
